### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by xbrabec** [kelseyhightower/vault-init#5]
I've deploed the vault-init based on the howto from https://github.com/kelseyhightower/vault-on-google-kubernetes-engine.

But the memory consuption of the vault-init scripts seem to be ever growing, untill the k8s memory limit kicks in and kills the container. Than all starts over again.

![image](https://user-images.githubusercontent.com/1808018/40891181-83cd660c-6781-11e8-9194-fb4b33f6f871.png)

```
name: vault-init
resources:
    limits:
        cpu: 100m
        memory: 512M
    requests:
        cpu: 10m
        memory: 128M
```
